language: go
go:
- 1.7.x
- 1.8.x
- master
before_install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- sh coverage.sh
env:
  global:
    secure: gg2CvudfbjwwJChvEn6Jna88NaV/faNzi+y++PkqVVkeSREI5q3O3w7U7Y8SsnccBQcSI7syYnk/C2a49zTemU8B7S/x9hlstMUnRXCNjN2LqWmmUmH0LpsHhwFCU7BUhW5W3bn4oYdM9iMPml+7VRdbUO+mj0oNk0edyKLBA6dO8fvSEPCrw2L5ErXUelN5ZrPiY1+Z3T8y2ZCpUeU5OagaeonD1inqD0mRNRjADRgv3wh5m9O9RXQGohvKI/U8Tagqir8TLVfQlRDWolitDlI3GO2+SbrmaoYBk6w2kWXPhFRHYNILk/SKtuj0Yfm4whgk1V2Cdv+RlbA0zsexghVjJ7OfV9Egj+mmZstmqzz5+L9lcwtItcC4NfziuPyhKsOFoZBWH8q0nitgP+UXlMqxMx723zSDDkrjbnbbN0S6wRGPRY7lMVLlovG4DiDdF3+u1UOvYv0lXupNS3lQEU2VlXwQHM8yXxEAH6iXmd7heqVwj7Qkr0UceslStjUO+SGy8OJxHBa4hfrcdQHroUbAQ41u7ja9QhrlMS6usxzyRPgBSDqTG8ZF10wxZkvGSv6KKhZusvIbL+r7Wsf4dB46diV/JrxsSvQRSsuq/N+J1e+UN5H6+qDIv20/5rO5qUQriPxpAze4KI15/PcxDimIiWz+XOdYNsQFllWOeZE=
